//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Nucleotide_v3.States
{
    [Serializable]
    public abstract class ChosenEdgeNodeState : EdgeNodeState
    {
        //private static volatile ChosenEdgeNodeState instance = null;
        
        protected ChosenEdgeNodeState()
        {
        
        }

        
    }
}

