//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Nucleotide_v3.States
{
    [Serializable]
    /// <summary>
    /// Don't use this class! Use the MaleChosenVertexNodeState or FemaleChosenVertexNodeState!
    /// 
    /// This class needs methods for inspecting neighboring vertices.
    /// </summary>
    public abstract class ChosenVertexNodeState : VertexNodeState
    {
        //private static volatile ChosenVertexNodeState instance = null;
	
        //public virtual List<int> IncidentUnchosenVertexPositions
        //{
        //    get;
        //    set;
        //}

        protected ChosenVertexNodeState()
        {
        
        }
        
    }
}

