//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nucleotide_v3.Model;

namespace Nucleotide_v3.States
{
    [Serializable]
    public class CutEdgeNodeState : EdgeNodeState
    {
        private static volatile CutEdgeNodeState instance = null;

        private CutEdgeNodeState()
        {
        
        }
        public static CutEdgeNodeState Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new CutEdgeNodeState();
                }
                return instance;
            }
        }
        [Obsolete("Warning: Use the other overload. This affects a flyweight.")]
        protected internal override void Reset(EdgeNodeStateContext context)
        {
            base.Reset(context);
        }

        protected internal override void Reset<E>(E context, EdgeNodeStateContextContainer<E> contextContainer)
        {
            base.Reset(context, contextContainer);
        }
    }
}

