//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nucleotide_v3.Model;

namespace Nucleotide_v3.States
{
    [Serializable]
    public class NodeState
    {
        protected internal virtual void ChangeState(NodeStateContext context, NodeState nodeState)
        {
            context.ChangeState(nodeState);
        }

        public enum NodeGender
        {
            Male,
            Female
        }
      
    }
}

