//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Nucleotide_v3.Model;

namespace Nucleotide_v3.States
{
    [Serializable]
    public class UnchosenEdgeNodeState : EdgeNodeState
    {
        private static volatile UnchosenEdgeNodeState instance = null;
        [Obsolete("Warning: Use the other overload. This affects a flyweight.")]
        protected internal override void Cut(EdgeNodeStateContext context)
        {
            base.Cut(context);
        }

        protected internal override void Cut<E>(E context, EdgeNodeStateContextContainer<E> contextContainer)
        {
            base.Cut(context, contextContainer);
        }
        [Obsolete("Warning: Use the other overload. This affects a flyweight.")]
        protected internal override void Choose(NodeStateContext context, NodeGender gender)
        {
            base.Choose(context, gender);
        }

        protected internal override void Choose<E>(E context, NodeGender gender, EdgeNodeStateContextContainer<E> contextContainer)
        {
            base.Choose(context, gender, contextContainer);
        }

        private UnchosenEdgeNodeState() // defeats outside instantiation
        {
        
        }

        public static UnchosenEdgeNodeState Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new UnchosenEdgeNodeState();
                }
                return instance;
            }
        }
    }
}

