//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Nucleotide_v3.Model
{
    [Serializable]
    public class EdgeNode : Node
    {
        public EdgeNode() : base()
        {
            
        }
        public EdgeNode(int position) : base(position)
        {
        }
    }

}

