//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Nucleotide_v3.States;

namespace Nucleotide_v3.Model
{
    public class EdgeNodeStateContextFactory<E> : NodeStateContextFactory<E> where E:EdgeNodeStateContext, new()
    {
        
        public override E ConstructDefaultNodeContext(int nodePosition)
        {
            var factory = EdgeNodeFactory.GetFactory();
            var context = ConstructNodeContext(
                            nodePosition: nodePosition,
                            nodeState: UnchosenEdgeNodeState.Instance,
                            nodeFactory: factory);
            return context;
        }

        public override E ConstructNodeContext<N>(int nodePosition, NodeState nodeState, NodeFactory<N> nodeFactory)
        {
            return base.ConstructNodeContext(nodePosition, nodeState, nodeFactory);
        }

        public E ConstructNodeContext(int nodePosition, NodeState nodeState)
        {
            var nodeFactory = EdgeNodeFactory.GetFactory();
            return base.ConstructNodeContext(nodePosition, nodeState, nodeFactory);
        }
        
    }
}

