//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Nucleotide_v3.States;

namespace Nucleotide_v3.Model
{
    [Serializable]
    /// <remarks>The int in the Values dictionary is for the NodePositionId</remarks>
    public class EdgeNodeStateContextContainer<E> : NodeStateContextContainer<E> 
        where E:EdgeNodeStateContext, new()
    {

        protected internal EdgeNodeStateContextContainer()
        {
            Values = new Dictionary<int, E>();
        }
        protected internal EdgeNodeStateContextFlyweightFactory<E> ContextFactory
        {
            get { return EdgeNodeStateContextFlyweightFactory<E>.GetInstance; }
        }
        /// <summary>
        /// This method takes the given context and updates the container to use a context with the new state.
        /// </summary>
        /// <param name="context"></param>
        /// <param name="state"></param>
        public void ChangeStateContext(NodeStateContext context, NodeState state)
        {
            var newContext = ContextFactory.ConstructNodeContext(context.Position, state);
            this.Update(context.Position, newContext);
            
        }
        protected internal IEnumerable<E> GetEdgeNodesWithState(NodeState state)
        {
            var nodeContexts = this.Values.Values.Where(t => t.State == state);
            return nodeContexts;
        }
        public EdgeNodeStateContextContainer<E> Copy()
        {
            var container = new EdgeNodeStateContextContainer<E>();
            foreach (var nodeStateContext in this.Values)
            {
                container.Values.Add(nodeStateContext.Key, nodeStateContext.Value.Copy<E>(nodeStateContext.Value, ContextFactory));
            }
            return container;
        }
        public EdgeNodeStateContextContainer<E> Copy(
            EdgeNodeStateContextFactory<E> factory)
        {
            var container = new EdgeNodeStateContextContainer<E>();
            foreach (var nodeStateContext in this.Values)
            {
                container.Values.Add(nodeStateContext.Key, nodeStateContext.Value.Copy<E>(nodeStateContext.Value, factory));
            }
            return container;
        }
        protected internal virtual void Choose(E context, NodeState.NodeGender gender)
        {
            context.State.Choose<E>(context, gender, this);
        }

        public virtual void ChooseAsMale(E context)
        {
            context.State.ChooseAsMale(context, this);
        }

        public virtual void ChooseAsFemale(E context)
        {
            context.State.ChooseAsFemale(context, this);
        }
        public virtual void Reset(E context)
        {
            context.State.Reset(context, this);
        }

        public virtual void Cut(E context)
        {
            context.State.Cut(context, this);
        }
    }
}

