//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nucleotide_v3.Model
{
    [Serializable]
    public class Node
    {
        public Node()
        {
            
        }

        protected Node(int position)
        {
            Position = position;
        }

        public Node(int value, int clause, int position)
        {
            Value = value;
            Clause = clause;
            Position = position;
        }

        public int Position { get; set; }
        public int Clause { get; set; }
        public int Value { get; set; }
        public HashSet<int> ValueSet { get; set; }
    }
}

