//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Nucleotide_v3.Model
{
    /// <remarks>Flyweight factories</remarks>
    public class VertexNodeFactory : NodeFactory<VertexNode>
    {
        private VertexNodeFactory() // defeats instantiation outside of GetFactory() method.
        {
            if (this.Values == null)
            {
                this.Values = new Dictionary<int, VertexNode>();
            }
        }

        public static VertexNodeFactory GetFactory()
        {
            if (Instance == null)
            {
                Instance = new VertexNodeFactory();

            }
            return (VertexNodeFactory) Instance;
        }

        //public new Dictionary<int, VertexNode> Values { get; set; }
        //public virtual IEnumerable<VertexNode> VertexNode
        //{
        //    get;
        //    set;
        //}
    }
}

