//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Security.Policy;

namespace Nucleotide_v3.Model
{
    [Serializable]
    public class VertexNode : Node
    {
        public VertexNode() : base()
        {
            
        }
        public VertexNode(int position) : base(position)
        {
            
        }
    }
}

